version: '2.2'
services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.10
    container_name: elasticsearch1
    environment: 
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./es-config-development.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks: 
      - esnet
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
  
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.10
    container_name: kibana1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes: 
      - ./kb-config-development.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - esnet
    healthcheck:
      test: curl -s http://localhost:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.10
    container_name: logstash1
    environment:
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata1:/usr/share/logstash/data
      - ./ls-config-development.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash-files/:/opt
      - ./logstash-pipelines/:/usr/share/logstash/pipeline  
    ports: 
      - 5044:5044
      - 9600:9600
    networks:
      - esnet
    depends_on:
      - elasticsearch

volumes:
  esdata1:
  lsdata1:

networks: 
  esnet: