---
# Default Kibana configuration from kibana-docker.

server.name: kibana1
server.host: "0"
xpack.security.enabled: false
xpack.monitoring.enabled: false
elasticsearch.url: http://elasticsearch1:9200
elasticsearch.username: elastic
elasticsearch.password: changeme
xpack.monitoring.ui.container.elasticsearch.enabled: false